### ISSUE TITLE
How much zoom is applied?

### ISSUE THREAD

**Issue by JobaDiniz** [wieslawsoltes/PanAndZoom#10]
How do I get how much zoom is applied?

**Comment by wieslawsoltes** [comment]
Currently there is no property exposed with current zoom value. I should probably add this. I only use InvalidatedChild callback action which is called everytime zoom changes. First two parameters are zoom in X and Y axis, last two are current pan offsets in X and Y axis.

**Comment by wieslawsoltes** [comment]
It will be possible using following properties:
```C#
/// <summary>
/// Gets the zoom ratio for x axis.
/// </summary>
double ZoomX { get; }

/// <summary>
/// Gets the zoom ratio for y axis.
/// </summary>
double ZoomY { get; }

/// <summary>
/// Gets the pan offset for x axis.
/// </summary>
double OffsetX { get; }

/// <summary>
/// Gets the pan offset for y axis.
/// </summary>
double OffsetY { get; }
```
after #12 PR will be merged.

**Comment by JobaDiniz** [comment]
Hi, those properties should be *"bindable"*, that is, they should be **DependencyProperty** otherwise I cannot bind to them.

Can you make these changes?

**Comment by wieslawsoltes** [comment]
@JobaDiniz Fixed in master.
