### ISSUE TITLE
using ZoomBorder as ItemsPanelTemplate for ItemsContro.ItemsPanel

### ISSUE THREAD

**Issue by mnusr** [wieslawsoltes/PanAndZoom#17]
Hi, 

how do i use ZoomBorder as ItemsPanelTemplate for ItemsContro.ItemsPanel?

```
<ItemsControl.ItemsPanel>
        <ItemsPanelTemplate>
            <paz:ZoomBorder />
        <ItemsPanelTemplate>
<ItemsControl.ItemsPanel>
```

at the moment it gives me the following exception:
InvalidOperationException: VisualTree of ItemsPanelTemplate must contain a Panel. 'Wpf.Controls.PanAndZoom.ZoomBorder' is not a Panel.

Thanks for your help.

**Comment by wieslawsoltes** [comment]
ZoomBorder derives from Border control which only supports single Child control. You need to wrap your ItemsControl inside of ZoomBorder control.
