### ISSUE TITLE
Nuget package fails compile, because packages are missing classes.

### ISSUE THREAD

**Issue by AndrueCope** [wieslawsoltes/PanAndZoom#18]
It works but there's a problem when I zoom in the image expands outside of its original area and fills the entire window. Xaml also attached.

Images attached. Note how the image 'underlaps' the buttons when zoomed in :-/
![afterzoom](https://user-images.githubusercontent.com/16834359/42101410-f403b028-7bba-11e8-9041-00363c9cdf6a.png)
![before](https://user-images.githubusercontent.com/16834359/42101411-f41c7bbc-7bba-11e8-8462-820b9f0b607b.png)

[PictureViewer.txt](https://github.com/wieslawsoltes/PanAndZoom/files/2150005/PictureViewer.txt)

**Comment by wieslawsoltes** [comment]
Set `ClipToBounds="True"` on control or parent.

https://github.com/wieslawsoltes/PanAndZoom/blob/c93ea85be8ec5042d0f045fad241e9bac363a921/samples/WpfDemo/MainWindow.xaml#L52

**Comment by AndrueCope** [comment]
Thank you!
