### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Crewman123** [wieslawsoltes/PanAndZoom#19]
There is a small copy paste issue in Wpf.Controls.PanAndZoom/ZoomBorder.cs at line 65

 public double ZoomY => (double)GetValue(ZoomXProperty);

should be Zoom**Y**Property probably

**Comment by wieslawsoltes** [comment]
@Crewman123 Thanks! Fixed via https://github.com/wieslawsoltes/PanAndZoom/commit/a6ef98ca0301d66ae722b8a04fdf8c1b825dc12a
