### ISSUE TITLE
Pan Constraints Relative to Child Size

### ISSUE THREAD

**Issue by outlookhazy** [wieslawsoltes/PanAndZoom#21]
Is there a straightforward way to limit the x/y min offset to prevent the child edges from actually entering the border?

What i'm trying to accomplish is limiting pan/zoom so that the child (image in my case) always touches each edge of the container. In my use case, there is no reason for the right edge of the child element to be halfway across the border (for example)
 
I can _almost_ do this by setting MinZoomX/Y to 1 and MaxOffsetX/Y to 0, but MinOffsetX/Y depend on both the content size and the ZoomX/Y level at any given point.
I managed to get the value calculated in a **ugly** converter call, binding against the zoom value in xaml, but returning that new minimum when bound to the zoom doesn't work (i'm getting an immediate second call with zoom 1 after returning the min offset value)

**Comment by wieslawsoltes** [comment]
@outlookhazy It probably is possible, just not yet implemented.

**Comment by outlookhazy** [comment]
@wieslawsoltes understood, I wasn't sure if maybe I was missing something. Thanks for sharing!

**Comment by csjturbine** [comment]
@outlookhazy , @wieslawsoltes I'm having a similar issue.  I don't want users to be able to pan past the right edge of an image inside the zoom control.  Any guidance on how to restrict this would be greatly appreciated.  BTW I love this user control.

**Comment by wieslawsoltes** [comment]
@csjturbine I would start by looking at the existing constraints:
https://github.com/wieslawsoltes/PanAndZoom/blob/18ce5d320bcbc4c00983114f2cddaeef2def4838/src/PanAndZoom/IPanAndZoom.cs#L58-L101
https://github.com/wieslawsoltes/PanAndZoom/blob/18ce5d320bcbc4c00983114f2cddaeef2def4838/src/Wpf.Controls.PanAndZoom/ZoomBorder.cs#L511-L550
https://github.com/wieslawsoltes/PanAndZoom/blob/18ce5d320bcbc4c00983114f2cddaeef2def4838/src/Avalonia.Controls.PanAndZoom/ZoomBorder.cs#L461-L508

You have to add proper support for constraints relative to child size to IPanAndZoom:than implement for both WPF and Avalonia frameworks.
