### ISSUE TITLE
[Feature request] zooming using pinch-to-zoom on touch devices

### ISSUE THREAD

**Issue by ashelleyPurdue** [wieslawsoltes/PanAndZoom#24]
Currently, the only way to zoom is to use a scroll wheel.  While this is wonderful on the Desktop, I'm pretty hosed when it comes to using my Surface.  Is there any chance you can adapt this to work with pinch-to-zoom?

**Comment by wieslawsoltes** [comment]
I don't have touch device to test this feature. So this is currently low priority, also AvaloniaUI doesn't support touch.
