### ISSUE TITLE
P&Z Border works differently with a Canvas or an Image

### ISSUE THREAD

**Issue by AeroClassics** [wieslawsoltes/PanAndZoom#26]
When I use the ZoomBorder with a Canvas everything works quite well, but when I use it with an Image the image is cropped and shows only in the upper left of the window. Am I doing something wrong or is there a problem? Do I need to do something different if the ZoomBorder contains an Image?

Thanks,
Doug

**Comment by gorogbalazs** [comment]
Not sure if this is the same problem, but if I add any control to the zoomborder that is bigger than the zoomborder size, it does the same: only displays the upper left part if I zoom in. I tried ItemsControl, Canvas and Border. Probably what you see with your image is the same. 
If I maximize my window though, ArrangeOverride is called and everything is drawn fine (I guess only as long as the content is not bigger than the zoomborder).
@AeroClassics have you found a workaround yet?

**Comment by gorogbalazs** [comment]
I have the same with ItemsControl. This code works as expected:
`        <paz:ZoomBorder Name="zoomBorder" Stretch="None" ZoomSpeed="1.2" 
                        Background="SlateBlue" ClipToBounds="True" Focusable="True"
                        VerticalAlignment="Stretch" HorizontalAlignment="Stretch" 
                        Grid.Row="4" Grid.Column="1">
            <Canvas Width="1122" Height="793">
                <Canvas.Background>
                    <VisualBrush TileMode="Tile" Viewport="-1,-1,20,20" ViewportUnits="Absolute" Viewbox="-1,-1,20,20" ViewboxUnits="Absolute">
                        <VisualBrush.Visual>
                            <Grid Width="20" Height="20" Background="Beige">
                                <Ellipse Height="2" Width="2" Stroke="Black" StrokeThickness="1" HorizontalAlignment="Left" VerticalAlignment="Top" Margin="-1,-1" />
                            </Grid>
                        </VisualBrush.Visual>
                    </VisualBrush>
                </Canvas.Background>
                <Rectangle Width="1122" Height="793" Stroke="Black" StrokeThickness="2" Fill="Transparent" />
            </Canvas>
        </paz:ZoomBorder>
![2nd_sample](https://user-images.githubusercontent.com/12424988/71444980-3169c300-2716-11ea-9b60-1147797107b0.png)
![1st_sample](https://user-images.githubusercontent.com/12424988/71444982-32025980-2716-11ea-867c-773ced523780.png)

`

This one only renders the upper left part of the control that was visible at startup (or window resize):
`        <paz:ZoomBorder Name="zoomBorder" Stretch="None" ZoomSpeed="1.2" 
                        Background="SlateBlue" ClipToBounds="True" Focusable="True"
                        VerticalAlignment="Stretch" HorizontalAlignment="Stretch" 
                        Grid.Row="4" Grid.Column="1">
            <ItemsControl Width="1122" Height="793">
                <ItemsControl.ItemsPanel>
                    <ItemsPanelTemplate>
                        <Canvas>
                            <Canvas.Background>
                                <VisualBrush TileMode="Tile" Viewport="-1,-1,20,20" ViewportUnits="Absolute" Viewbox="-1,-1,20,20" ViewboxUnits="Absolute">
                                    <VisualBrush.Visual>
                                        <Grid Width="20" Height="20" Background="Beige">
                                            <Ellipse Height="2" Width="2" Stroke="Black" StrokeThickness="1" HorizontalAlignment="Left" VerticalAlignment="Top" Margin="-1,-1" />
                                        </Grid>
                                    </VisualBrush.Visual>
                                </VisualBrush>
                            </Canvas.Background>
                        </Canvas>
                    </ItemsPanelTemplate>
                </ItemsControl.ItemsPanel>
                <Rectangle Width="1122" Height="793" Stroke="Black" StrokeThickness="2" Fill="Transparent" />
            </ItemsControl>
        </paz:ZoomBorder>`

**Comment by gorogbalazs** [comment]
I found this workaround:


        <paz:ZoomBorder Name="zoomBorder" Stretch="None" ZoomSpeed="1.2" 
                    Background="SlateBlue" ClipToBounds="True" Focusable="True"
                    VerticalAlignment="Stretch" HorizontalAlignment="Stretch" 
                    Grid.Row="4" Grid.Column="1">
            <Canvas>
                <Canvas Width="1122" Height="793" Canvas.ZIndex ="0" >
                    <Canvas.Background>
                        <VisualBrush TileMode="Tile" Viewport="-1,-1,20,20" ViewportUnits="Absolute" Viewbox="-1,-1,20,20" ViewboxUnits="Absolute">
                            <VisualBrush.Visual>
                                <Grid Width="20" Height="20" Background="Beige">
                                    <Ellipse Height="2" Width="2" Stroke="Black" StrokeThickness="1" HorizontalAlignment="Left" VerticalAlignment="Top" Margin="-1,-1" />
                                </Grid>
                            </VisualBrush.Visual>
                        </VisualBrush>
                    </Canvas.Background>
                </Canvas>
                <ItemsControl Width="1122" Height="793" Canvas.ZIndex="1">
                    <ItemsControl.ItemsPanel>
                        <ItemsPanelTemplate>
                            <Canvas Background="Transparent" />
                        </ItemsPanelTemplate>
                    </ItemsControl.ItemsPanel>
                    <Rectangle Width="1122" Height="793" Stroke="Black" StrokeThickness="2" Fill="Transparent" />
                    <Rectangle Width="20" Height="20" Stroke="Red" StrokeThickness="2" Fill="Yellow" Margin="700,700" />
                </ItemsControl>
            </Canvas>            
        </paz:ZoomBorder>
