### ISSUE TITLE
How PanTo() works?

### ISSUE THREAD

**Issue by gosha20777** [wieslawsoltes/PanAndZoom#27]
I want to go up, when I press up button.
My code is:
```csharp
...
namespace AvaloniaDemo
{
    public class MainWindow : Window
    {
        private ZoomBorder zoomBorder;

        public MainWindow()
        {
            ...
            zoomBorder = this.Find<ZoomBorder>("zoomBorder");
            zoomBorder.KeyDown += ZoomBorder_KeyDown;
        }
       ...

        private void ZoomBorder_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Up)
            {
                zoomBorder.PanTo(0, -0.1) // I want to go up
            }
            if (e.Key == Key.Down)
            {
                zoomBorder.PanTo(0, 0.1) // I want to go down
            }
            if (e.Key == Key.Left)
            {
                zoomBorder.PanTo(0.1, 0) // I want to go left
            }
            if (e.Key == Key.Right)
            {
                zoomBorder.PanTo(-0.1, 0) // I want to go right
            }
        }
    }
}
```

**Comment by wieslawsoltes** [comment]
You need to call each time:
```C#
StartPan(point.X, point.Y);
```

**Comment by gosha20777** [comment]
It steel not work.
I've replace `zoomBorder.PanTo(0, 0.5)` to `zoomBorder.StartPan(0, 0.5)` and it dose not work. Nothing happens.

**Comment by wieslawsoltes** [comment]
> @wieslawsoltes , It steel not work.
> I've replace `zoomBorder.PanTo(0, 0.5)` to `zoomBorder.StartPan(0, 0.5)` and it dose not work. Nothing happens.
> 
> P.s. I've tried to use this method before but there is also no results.

You have to call
```
StartPan(...)
PanTo(...)
```

**Comment by gosha20777** [comment]
@wieslawsoltes Nothing happens.

So my code is:
```CSharp
//Zoomer class
public static void MoveTo(double x, double y)
 {
      _zoomBorder?.StartPan(x,y);
      _zoomBorder?.PanTo(x,y);
 }
...

//MainWindow class
private void ZoomBorder_KeyDown(object sender, KeyEventArgs e)
{
      switch (e.Key)
      {
                case Key.R:
                    Zoomer.Reset();
                    break;
                case Key.Up:
                    Zoomer.MoveTo(0, -0.5);
                    break;
                case Key.Down:
                    Zoomer.MoveTo(0, 0.5);
                    break;
                case Key.Left:
                    Zoomer.MoveTo(-0.5, 0);
                    break;
                case Key.Right:
                    Zoomer.MoveTo(0.5, 0);
                    break;
      }
}
```
- If I remove line `StartPan()` and stay only `PanTo();` it works very strange. It does not work correctly. It moves to the random(?) position.
- If I remove line `PanTo()` and stay only `StartPan();` it dose not work. Nothing happens.
- If I call `StartPan()` before `PanTo()` it dose not work. Nothing happens.
- If I call `PanTo()` before `StartPan()` it does not work correctly. It moves to the random(?) position. 

https://github.com/gosha20777/rescuer-la - here is my project

https://github.com/gosha20777/rescuer-la/blob/dev_desktopApp/RescuerLaApp/Views/MainWindow.xaml - Here is Xaml file 

https://github.com/gosha20777/rescuer-la/blob/dev_desktopApp/RescuerLaApp/Views/MainWindow.xaml.cs - Here is Xaml.sc file *MainWindow class*

https://github.com/gosha20777/rescuer-la/blob/dev_desktopApp/RescuerLaApp/Models/Zoomer.cs - Here is *Zoomer class*.

**Comment by wieslawsoltes** [comment]
Try:
```C#
public static void MoveTo(double x, double y)
 {
      _zoomBorder?.StartPan(0,0);
      _zoomBorder?.PanTo(x,y);
 }
```

**Comment by gosha20777** [comment]
I cant understand
1. Which X and Y I should put into StartPan() and PanTo() functions to go directly up when i press e.g. UP button on the keyboard.
2. Why when I call StartPan() before PanTo() it does not work?
3. Should I put defriend points X and Y to StartPan() \ PanTo() (e.g. StartPan(X1, Y1); PanTo(X2, Y2)?

**Comment by wieslawsoltes** [comment]
https://github.com/wieslawsoltes/PanAndZoom/blob/4794df21a3be69d2f1c2fb09660b43bd209f110d/src/Avalonia.Controls.PanAndZoom/ZoomBorder.cs#L564
https://github.com/wieslawsoltes/PanAndZoom/blob/4794df21a3be69d2f1c2fb09660b43bd209f110d/src/Avalonia.Controls.PanAndZoom/ZoomBorder.cs#L570-L571

**Comment by wieslawsoltes** [comment]
The intended use was only for mouse manipulation not from code behind by user. So the API assumes you always call `StartPan` with initial pan position and later call `PanTo` with new position. The `PantTo` than calculates delta of `StartPan` initial position and `x` and `y` coordinates provided to `PanTo`.

**Comment by gosha20777** [comment]
Yes I understand. It works. Thank you sooooooooooooooo much!
