### ISSUE TITLE
Pan Lock

### ISSUE THREAD

**Issue by aselby** [wieslawsoltes/PanAndZoom#32]
A feature request:

Make it so that you can't pan the image off the screen, if you look at how windows 10 photos works a feature like that would be awesome.

**Comment by wieslawsoltes** [comment]
You can set `EnablePan=false` to enable pan lock.

https://github.com/wieslawsoltes/PanAndZoom/blob/e414b2ac5b41b8cc35fcb9ee70dd511e583750d8/src/PanAndZoom/IPanAndZoom.cs#L104
