### ISSUE TITLE
ScrollViewer support  for ZoomBorder

### ISSUE THREAD

**Issue by RomanSoloweow** [wieslawsoltes/PanAndZoom#34]

**Comment by wieslawsoltes** [comment]
I do not have implementation for ScrollViewer.

For pan and zoom I am using RenderTransform:

https://github.com/wieslawsoltes/PanAndZoom/blob/fd3151b43bda60c6db4b3f04b1e0acc94fe35f6e/src/Avalonia.Controls.PanAndZoom/ZoomBorder.cs#L565-L567

and internally I use Matrix for calculation:

https://github.com/wieslawsoltes/PanAndZoom/blob/fd3151b43bda60c6db4b3f04b1e0acc94fe35f6e/src/Avalonia.Controls.PanAndZoom/ZoomBorder.cs#L22

PR is welcome.

**Comment by wieslawsoltes** [comment]
Initial support added into master.

**Comment by DavidBergstromSWE** [comment]
To be useful, WPF control is also in need of ScrollViewer support. Any plans for adding this?

**Comment by wieslawsoltes** [comment]
> To be useful, WPF control is also in need of ScrollViewer support. Any plans for adding this?

WPF control is no longer under active development.
