### ISSUE TITLE
EnablePan not found

### ISSUE THREAD

**Issue by RomanSoloweow** [wieslawsoltes/PanAndZoom#35]

**Comment by wieslawsoltes** [comment]
You need to use nightly build feed, not yet released as stable.

https://github.com/wieslawsoltes/PanAndZoom#nuget

**Comment by RomanSoloweow** [comment]
Can you help me with zoom for [SimpleStateMachineNodeEditor](https://github.com/SimpleStateMachine/SimpleStateMachineNodeEditor) please. It's [issue](https://github.com/SimpleStateMachine/SimpleStateMachineNodeEditor/issues/15)
