### ISSUE TITLE
Bug: some move after reaching  max or min zoom

### ISSUE THREAD

**Issue by RomanSoloweow** [wieslawsoltes/PanAndZoom#36]
After reaching  max or min zoom on MouseWheel we have some translate for our elements.

I think this is because we continue to set CenterX and CenterY for ScaleTransform after reaching  max or min.

We need just block it if zoom value already max or min.

**Comment by wieslawsoltes** [comment]
You can set property  `EnableConstrains=true` and set properties for required zoom limits `MinZoomX`, `MaxZoomX`, `MinZoomY` , `MaxZoomY`.

https://github.com/wieslawsoltes/PanAndZoom/blob/e414b2ac5b41b8cc35fcb9ee70dd511e583750d8/src/PanAndZoom/IPanAndZoom.cs#L59

https://github.com/wieslawsoltes/PanAndZoom/blob/e414b2ac5b41b8cc35fcb9ee70dd511e583750d8/src/PanAndZoom/IPanAndZoom.cs#L61-L79

**Comment by Joaoo1** [comment]
I am still having the same problem, when reaches the MaxZoom, if i keep trying to zoom in, it will pan to another place. 

I already setted the property `EnableConstrains=true` and the properties `MinZoomX`, `MaxZoomX`, `MinZoomY `, `MaxZoomY`.
