### ISSUE TITLE
ZoomIn and ZoomOut methods

### ISSUE THREAD

**Issue by RomanSoloweow** [wieslawsoltes/PanAndZoom#37]
These methods simply add or reduce the previously set step to zoom.

**Comment by wieslawsoltes** [comment]
Added https://github.com/wieslawsoltes/PanAndZoom/blob/e414b2ac5b41b8cc35fcb9ee70dd511e583750d8/src/PanAndZoom/IPanAndZoom.cs#L139-L147

Will be available in next stable release, currently available in previews.
