### ISSUE TITLE
Documentations 

### ISSUE THREAD

**Issue by RomanSoloweow** [wieslawsoltes/PanAndZoom#39]
We don't have description for methods off control.

**Comment by wieslawsoltes** [comment]
Looks at https://github.com/wieslawsoltes/PanAndZoom/blob/master/src/PanAndZoom/IPanAndZoom.cs, the intellisense is VS should pick those.

**Comment by wieslawsoltes** [comment]
If anyone wan't to contribute documentation please submit PR, I have currently no plans, there are API intellisense docs and sample apps.
