### ISSUE TITLE
Child.Size == ZoomBorder.Size and Save zoom

### ISSUE THREAD

**Issue by Art77** [wieslawsoltes/PanAndZoom#4]
Good afternoon. Torments me one question how it is possible to stretch the container/component after the zoom to the size ZoomBorder, while maintaining the output of the zoom?

**Comment by wieslawsoltes** [comment]
Not sure what is your question. You can set `AutoFitMode` property for different zoom behavior.

You have three options here:
* `AutoFitMode="None"` for manual zoom
* `AutoFitMode="Extent"` automatic zoom to maintain aspect ration of control
* `AutoFitMode="Fill"`  automatic zoom to fill container

**Comment by Art77** [comment]
See no difference :(

**Comment by wieslawsoltes** [comment]
@Art77 Could you provide example of what you want achieve with zoom control, this would help solving the issue.

**Comment by Art77** [comment]
Container (Canvas) contains components in this case, the gears and DB (what style does not matter), in addition to this data, container supports drag_and_drop, this is the problem I need to data container stretched to a size equal ZoomBorder, so as not to rewrite drag_and_drop and besides, I really like how ZoomBorder, and I find it very easy to sync it with map zooming. 
![default](https://cloud.githubusercontent.com/assets/18144011/24456500/e3f778fe-149b-11e7-90db-9163ca843df9.PNG)
![3](https://cloud.githubusercontent.com/assets/18144011/24456506/e4e26ef4-149b-11e7-814f-da6c44d93196.PNG)

**Comment by Art77** [comment]
Did not continue to dwell on this issue, and decided redefined DragAndDrob in ZoomBorder. The question can be closed.
