### ISSUE TITLE
ViewModel for realize MVVM

### ISSUE THREAD

**Issue by RomanSoloweow** [wieslawsoltes/PanAndZoom#40]
A class that will contain all the methods and fields.

**Comment by wieslawsoltes** [comment]
@RomanSoloweow For which MVVM framework? I don't think this is the scope of this project.

You can use https://github.com/wieslawsoltes/PanAndZoom/blob/da1b3a6a39e869fc4f782a35fdad563642b51eb0/src/PanAndZoom/IPanAndZoom.cs#L10

**Comment by RomanSoloweow** [comment]
We can realize INotifyPropertyChanged object and use it as datacontext for panzoomborder. I can try to do it

**Comment by wieslawsoltes** [comment]
I think we can close this issue, there is IPandAndZoom interface that should be sufficient.
