### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by RomanSoloweow** [wieslawsoltes/PanAndZoom#41]
How i can contribute in build, where we have EnablePan and EnableZoom?

**Comment by wieslawsoltes** [comment]
We have to wait for 0.10.0 release of Avalonia, otherwise you have to use nightly NuGet feed.

**Comment by RomanSoloweow** [comment]
Can i contribute to WPF?

**Comment by wieslawsoltes** [comment]
I am deprecating WPF version as I no longer use it and extend. Latest version is 2.3.3 and last one.

Last version is here: https://github.com/wieslawsoltes/PanAndZoom/tree/WPF

Also I am working on new version of ZoomControl, so this one will also be no longer updated

It will be based on https://github.com/wieslawsoltes/Draw2D/tree/master/src/Draw2D/Zoom

**Comment by RomanSoloweow** [comment]
PanAndZoom will only be for Avalonia?

**Comment by wieslawsoltes** [comment]
Not really Avalonia only. It will be just no longer actively developed as I mentioned above I am planning to do different version.

**Comment by RomanSoloweow** [comment]
Will the new version support WPF? 
When do you plan to release a new version?

**Comment by wieslawsoltes** [comment]
No plans for WPF version, the new version will be release as soon as Avalonia releases, currently there are preview builds released.

**Comment by wieslawsoltes** [comment]
I think original question for answered and fixed, and as there are no future plans for WPF releases I will close the issue. Please open new issues related to Avalonia builds or new features if needeed.
