### ISSUE TITLE
Using ZoomBorder inside the TabControl resets zoom and pan

### ISSUE THREAD

**Issue by dfkeenan** [wieslawsoltes/PanAndZoom#43]
Hi,

I am using the `ZoomBorder` control in a Tab. When I switch between tabs it resets the zoom and pan. I am not sure if this is an Avalonia issue or I am using the control wrong etc. I am currently on Avalonia 0.10-preview2.

Otherwise I really like this control. :)

Thanks,
dfkeenan

**Comment by wieslawsoltes** [comment]
Not sure, can you provide sample xaml?

**Comment by wieslawsoltes** [comment]
Did you try setting `Stretch` property to `None`? Default is `Uniform`.

**Comment by wieslawsoltes** [comment]
@dfkeenan This is fixed in `master` branch. You can try [nightly NuGet feed](https://pkgs.dev.azure.com/wieslawsoltes/GitHub/_packaging/CI/nuget/v3/index.json) or wait for next release of Avalonia (preview or stable).

**Comment by wieslawsoltes** [comment]
![2020-11-22_22-28-09](https://user-images.githubusercontent.com/2297442/99917956-1764a600-2d14-11eb-8b8a-adfd9acb9620.gif)
