### ISSUE TITLE
Most recent stable release requires Avalonia Beta version.

### ISSUE THREAD

**Issue by piotrek-b** [wieslawsoltes/PanAndZoom#45]
Hello,

I've came across this library and found it useful in the project, however - I'm not able to use the latest stable version (2.3.3). I'm using 2.3.2 instead. This is because of the fact that most recent version uses AvaloniaUI beta version `0.9.999-cibuild0006647-beta`. I don't think that's good if not needed, wouldn't 0.9.12 be enough? I would like to use `zoomChanged` event handler but it's not a part of 2.3.2 release.

```
Detected package downgrade: Avalonia from 0.9.999-cibuild0006647-beta to 0.9.12. Reference the package directly from the project to select a different version. 
 MyProj -> Avalonia.Controls.PanAndZoom 2.3.3 -> Avalonia (>= 0.9.999-cibuild0006647-beta) 
 MyProj -> Avalonia (>= 0.9.12)
```

**Comment by wieslawsoltes** [comment]
This looks like some issue with my automated CI system. Will do fix realease.

**Comment by wieslawsoltes** [comment]
Fixed version has been published https://www.nuget.org/packages/Avalonia.Controls.PanAndZoom/2.3.4

**Comment by piotrek-b** [comment]
This version does not include `ZoomChanged` event handler support, is this intentional?

**Comment by wieslawsoltes** [comment]
> This version does not include `ZoomChanged` event handler support, is this intentional?

This requires newer AvaloniaUI.  You can use 3.0.0-rc1

**Comment by piotrek-b** [comment]
Are there any docs on how to setup a project in newer Avalonia version? It seems that it's not compatible with previous version, it does not show any UI on build and run

**Comment by wieslawsoltes** [comment]
https://github.com/AvaloniaUI/Avalonia/wiki/Breaking-Changes#09---010

**Comment by piotrek-b** [comment]
Ok I went through it but I'm not able to run my app, I'm only able to build it. No errors, just nothing besides building happens.

`dotnet run` logs:

[log.txt](https://github.com/wieslawsoltes/PanAndZoom/files/5826441/log.txt/)

`Program.cs`:

```
using Avalonia;

namespace MyProject
{
    class Program


    {
        // Initialization code. Don't use any Avalonia, third-party APIs or any
        // SynchronizationContext-reliant code before AppMain is called: things aren't initialized
        // yet and stuff might break.
        public static void Main(string[] args) => BuildAvaloniaApp()
            .StartWithClassicDesktopLifetime(args);

        // Avalonia configuration, don't remove; also used by visual designer.
        public static AppBuilder BuildAvaloniaApp()
            => AppBuilder.Configure<App>()
                .UsePlatformDetect()
                .LogToTrace();
    }
}

```
