### ISSUE TITLE
Ambiguous reference with Avalonia 0.10.10 and PanAndZoom 4.3.0

### ISSUE THREAD

**Issue by maxkatz6** [wieslawsoltes/PanAndZoom#55]
![Screen Shot 2021-11-24 at 8 12 43 PM](https://user-images.githubusercontent.com/3163374/143334436-440d9979-e2f1-4b98-836d-b5f42f8f6ffa.png)
![Screen Shot 2021-11-24 at 8 12 54 PM](https://user-images.githubusercontent.com/3163374/143334446-91e19014-5c12-4957-a69f-59bbf5cd08d9.png)

**Comment by wieslawsoltes** [comment]
This was just temporary fix, will remove in next release. TheTransformOperationsTransition has been fixed in Avalonia, waiting for 0.10.11 release. Please use xmlns in the meantime. Will do service release 10.11.1-rc.1 shortly but it will require 0.10.11-rc.1 version of Avalonia.

**Comment by wieslawsoltes** [comment]
Fixed in master branch and in 10.11.1-rc.1 release
