### ISSUE TITLE
[WPF]Resizing the window resets the view

### ISSUE THREAD

**Issue by facelesspanda** [wieslawsoltes/PanAndZoom#7]
Hello,

I'm trying this control out, and I like how the zoom behaves with a static window, but whenever I change the size of the window, the zoomborder resets.

Xaml looks like this.
```xaml
        <paz:ZoomBorder x:Name="zoomBorder" AutoFitMode="None" ZoomSpeed="1.2" ClipToBounds="True"
                        Background="DarkGray"
                        VerticalAlignment="Stretch" HorizontalAlignment="Stretch">
            <Canvas x:Name="canvas">
                <Image x:Name="wp_img"/>
            </Canvas>
        </paz:ZoomBorder>
```

I thought "oh, maybe it's that auto-fit thing", so I copied the key input bit from the demo, and tried to fiddle, but whenever I enable "Extent" or "Fill", my image just disappears from view. Any idea what might be happening?

**Comment by wieslawsoltes** [comment]
@facelesspanda Fixed this issue in latest nightly build.
