### ISSUE TITLE
ScrollViewer's scrollBars not correct when setting when ZoomBorder's child Height is set

### ISSUE THREAD

**Issue by BobLd** [wieslawsoltes/PanAndZoom#70]
Hi @wieslawsoltes, thanks a lot for your amazing libraries.

It seems there's a bug in the `ZoomBorder` control when one sets the Height of it's child. The zooming and panning work but the `ScrollViewer`'s scrollBars are not correct.

I'm not sure if this is an actual bug or if I'm doing something wrong, or if the issue is in the `ScrollViewer`.

One way the reproduce the issue is as follow:
```axml
<ScrollViewer Name="MainScrollViewer"
			  VerticalScrollBarVisibility="Visible"
			  HorizontalScrollBarVisibility="Visible"
			  AllowAutoHide="False"
			  Background="Aquamarine">
	
	<paz:ZoomBorder Name="ZoomBorder" Stretch="Uniform" ZoomSpeed="1.2"
				   EnableConstrains="True"
				   Background="BurlyWood" ClipToBounds="True" Focusable="True"
				   VerticalAlignment="Stretch" HorizontalAlignment="Stretch" Margin="5"
				   MinZoomX="0.1" MinZoomY="0.1" MaxZoomX="50" MaxZoomY="50">
	
			<Canvas Name="MainCanvas" Background="Purple"
					Height="1000" Margin="5" />

	</paz:ZoomBorder>
</ScrollViewer>
```

When removing the `ZoomBorder` control, the `ScrollViewer`'s scrolbars are correct:
```axml
<ScrollViewer Name="MainScrollViewer"
			  VerticalScrollBarVisibility="Visible"
			  HorizontalScrollBarVisibility="Visible"
			  AllowAutoHide="False"
			  Background="Aquamarine">

		<Canvas Name="MainCanvas" Background="Purple"
				Height="1000" Margin="5" />

</ScrollViewer>
```

**Comment by BobLd** [comment]
There is in fact an issue when the Child is bigger than the view, not because the Height is set. I'm closing the issue as I'm now using a `LayoutTransformControl` to handle zooming

**Comment by SiMet** [comment]
Hi all,

I'd like to reopen this ticket. 
Using sample application I changed size of Border in first sample to fixed=1300,1300

I was expecting that scroll will appear. However, it's not visible.
![image](https://github.com/user-attachments/assets/9152e43a-9b49-42c8-8d72-a44f9252b43d)
![image](https://github.com/user-attachments/assets/62e1f0da-b486-4de0-b407-4886e9bf4978)

I'm not sure if it's issue of the lib or maybe I should do something to handle such cases.

**Comment by SiMet** [comment]
@wieslawsoltes quick search shows me that method `CalculateScrollable` does not care about Border size.
In my opinion viewport should be a value of `this.Border.Size` not the `_element.Border.Size`
