### ISSUE TITLE
ZoomBorder auto reset when switching Tabs

### ISSUE THREAD

**Issue by sonhai1710** [wieslawsoltes/PanAndZoom#79]
I'm testing the sample AvaloniaDemo.Desktop.exe and it has same problem with my code. So I'm confused this is the feature or not.
When I play around with Example 1 Tab, then click Example 2, and back to Example 1, the view is automatically reset, but the ZoomX, ZoomY, OffsetX, OffsetY value (on the right side) are not changed.
Can I keep the zoom and pan when switching tabs?
![image](https://github.com/wieslawsoltes/PanAndZoom/assets/34742789/d79398f5-ccb7-4e90-a795-2e0054065f8b)

**Comment by wieslawsoltes** [comment]
Its issue with TabControl

**Comment by wieslawsoltes** [comment]
Fixed by https://github.com/wieslawsoltes/PanAndZoom/commit/13b5e1437b864a0a07f311032bfed9a99d53be72
