### ISSUE TITLE
[WPF] Zoom inside tab stops to work

### ISSUE THREAD

**Issue by JobaDiniz** [wieslawsoltes/PanAndZoom#8]
I have 3 tabs, one of which `ZoomBorder` is defined.
When I start switching tabs, the `ZoomBorder` stops to work. I think this has something to do with the `Unload` event of `ZoomBorder`.

**Edit**
These [lines](https://github.com/wieslawsoltes/PanAndZoom/blob/0.5.1/src/Wpf.Controls.PanAndZoom/ZoomBorder.cs#L51-L60) are the issue. The library handles the `Unloaded` event however it should also handle the `Loaded` event.

**Edit 2**
The current *master* version also doesn't handle the `Loaded` event: [L112](https://github.com/wieslawsoltes/PanAndZoom/blob/master/src/Wpf.Controls.PanAndZoom/ZoomBorder.cs#L112)

**Comment by wieslawsoltes** [comment]
Thank you for reporting the issue. Will take a look as soon as possible.

**Comment by wieslawsoltes** [comment]
@JobaDiniz Could you try latest master, I have pushed support for `Loaded` event. You can use `NuGet` nightly feed for testing https://github.com/wieslawsoltes/PanAndZoom#nuget

**Comment by wieslawsoltes** [comment]
@JobaDiniz This should be fixed in latest master.
